int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int n);
int print_last_digit(int n);
int add(int a, int b);
void print_to_98(int n);
void jack_bauer(void);
void times_table(void);
void print_times_table(int n);
int mul(int a, int b);
void print_most_numbers(void);
void print_numbers(void);
int _isdigit(int c);
int _isupper(int c);
void print_line(int n);
void print_diagonal(int n);
